spring:
  h2:
    console:
      enabled: true
      path: /h2-console

  datasource:
    url: jdbc:h2:mem:hodolog;NON_KEYWORDS=USER
    username: sa
    password:
    driver-class-name: org.h2.Driver
    hikari:
      auto-commit: false
  jpa:
    hibernate:
      ddl-auto: create-drop
    defer-datasource-initialization: true
  sql:
    init:
      mode: always
      data-locations: classpath:data.sql

  data:
    web:
      pageable:
        max-page-size: 2000
        default-page-size: 5
        one-indexed-parameters: true
        

hodolman:
  hello:
    name: "승현김"
    home: "bucheon"
    hobby: "programming"

