### 로그인

POST http://localhost:8080/auth/login
Content-Type: application/json

{
  "email" : "dnfheh@naver.com",
  "password" : "1234"
}

###인증 페이지 요청
GET http://localhost:8080/foo
Content-Type: application/json
Cookie: SESSION=5611ca63-490d-4e3e-a8c1-6259c5b195b8

//JWT HS256 RS256 암호화 인코딩
#
#{
#   "alg" : "HS256",
#  "typ" : "JWT"
#}